config/routes.rb
Rails.application.routes.draw do
  root 'products#home'
  get 'home' => 'products#home'

  get 'oauths/oauth'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions

  resources :products do
    get 'imagedelete'
    collection do
      get 'home'
    end
  end
  resources :conversations
  resources :messages
  resources :trades

	resources :gardens, only: [:show, :new, :index, :create, :destroy]
  resources :users, only: [:show, :new, :create, :destroy, :edit, :update] #do
  #   member do
  #     get 'inbox' => 'user#inbox', :as => :inbox
  #   end
  # end

  get '/users/:id/inbox', to: 'users#inbox', as: 'inbox'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  before_save { self.email = email.downcase }
  # before_save { self.email = self.email.downcase }  # same as above
  # We can omit the 2nd self because Rails does this for us.

  # For AWS upload
  # mount_uploader :image, ImageUploader
  # mount_uploader :image, AssetUploader
  # after_save :enqueue

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  has_one :garden
  has_many :products, through: :garden
  has_many :messages, through: :product
  has_many :trades

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, presence: true
  validates :email, uniqueness: {case_sensitive: false}
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: "not a valid email address" }
  validates :name, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.first
      render :new
    end
  end

  def show
    @user = current_user
    @garden = Garden.new
  end

  def inbox
    @sent_conversations = Conversation.where("sender_id = ?", current_user.id)
    @received_conversations = Conversation.where("receiver_id = ?", current_user.id)
    @trades = Trade.where("seller_id = ?", current_user.id)
    @user = current_user

    # create a list of unique products
    @sent_products_list = Product.joins(:conversations).where("sender_id = ?", current_user.id).distinct
    @received_products_list = Product.joins(:conversations).where("receiver_id = ?", current_user.id).distinct
  end

  def destroy
    logout
    @user.garden.products.each do |product|
      product.destroy
    end
    @user.garden.destroy
    @user.destroy

    redirect_to root_path
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="register-form">
  <%= form_for(@user) do |f| %>
    <div class="register-field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="register-field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="register-field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="register-field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <% if current_user %>
      <div class="register-field">
        <%= f.label :avatar %>
        <%= f.file_field :image %>
      </div>
    <% end %>

    <%= render partial: 'shared/flash' %>
    <div class="register-action">
      <%= f.submit class: "create-user" %>
    </div>
  <% end %>
</div>

app/views/users/_message.html.erb
<li>
  <ul>
    <li>Sender: <%= message.sender.name %></li>
    <li>Title: <%= message.title %></li>
    <li>Message content:<%= message.content %></li>
    <li><%= link_to "Reply", message_path(message) %>
  </ul>
</li>

app/views/users/_userinfobox.html.erb
<div class="user-info">
  <ul>
    <li><%= link_to "#{@user.name}", garden_path(@user.garden) %></li>
    <li><%= @user.email %></li>
    <li><%= image_tag(@user.image_url(:thumb).to_s) %></li>
  </ul>
</div>

app/views/users/edit.html.erb
<h1 class="main-title">Edit Profile</h1>
<%= render 'form' %>

app/views/users/inbox.html.erb
<div class="user-controls">
  <%= button_to trades_path, method: 'get' do %>
    Ended Trades <span class="badge-success"><%= @trades.count %></span>
  <% end %>
</div>

<div class="conversations">
  <ul class="accordion-tabs">

    <li class="tab-header-and-content">
      <a href="javascript:void(0)" class="is-active tab-link">Their Requests</a>
      <div class="tab-content">
        <ul class="accordion">
          <%= render partial: 'conversations/conversations_accordion', locals: { products_list: @received_products_list, conversations: @received_conversations } %>
        </ul>
      </div>
    </li>

    <li class="tab-header-and-content">
      <a href="javascript:void(0)" class="tab-link">My Requests</a>
      <div class="tab-content">
        <ul class="accordion">
          <%= render partial: 'conversations/conversations_accordion', locals: { products_list: @sent_products_list, conversations: @sent_conversations } %>
        </ul>
      </div>
    </li>
  </ul>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="user-name">
    <h1><%= @user.name %></h1>
  </div>

  <div class="user-box">
    <% if !@user.image %>
      <div class="upload-pic">
        <%= form_for(@user) do |f| %>
          <div class="pic-upload">
            <%= f.label :"Upload Profile Picture" %>
            <%= f.file_field :image %>
          </div>
          <div class="change-pic-btn">
            <%= f.submit "Upload" %>
          </div>
        <% end %>
      </div>

    <% else %>
      <div class="user-pic">
        <%= image_tag(@user.image_url(:thumb).to_s) %>
      </div>
      <div class="upload-pic">
        <%= form_for(@user) do |f| %>
          <div class="pic-upload">
            <%= f.label :"Change Profile Picture" %>
            <%= f.file_field :image %>
          </div>
          <div>
            <%= f.submit "Upload" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="edit-profile">
      <%= link_to "Edit Profile", edit_user_path(@user) %>
    </div>

    <% if !@user.garden %>
      <div class="create-garden">
        <p>Create a Garden</p>
        <%= form_for(@garden) do |f| %>
          <div class="pic-upload">
            <%= f.label :postal_code %>
            <%= f.text_field :postal_code %>
          </div>
          <div class="create-garden-btn">
            <%= f.submit "Create Garden" %>
          </div>
        <% end %>
      </div>

    <% else %>
      <div class="edit-garden">
        <%= link_to "View Garden", garden_path(@user.garden) %> |
        <%= link_to "Delete Garden", garden_path(@user.garden), method: :delete, data: {confirm: "Are you sure you want to delete your garden?"} %>
      </div>
    <% end %>

  </div>
</div>