config/routes.rb
Rails.application.routes.draw do
  root 'products#home'
  get 'home' => 'products#home'

  get 'oauths/oauth'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions

  resources :products do
    get 'imagedelete'
    collection do
      get 'home'
    end
  end
  resources :conversations
  resources :messages
  resources :trades

	resources :gardens, only: [:show, :new, :index, :create, :destroy]
  resources :users, only: [:show, :new, :create, :destroy, :edit, :update] #do
  #   member do
  #     get 'inbox' => 'user#inbox', :as => :inbox
  #   end
  # end

  get '/users/:id/inbox', to: 'users#inbox', as: 'inbox'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :conversations
  belongs_to :garden
  belongs_to :trade
  validates :name, presence: true
  
  # For AWS upload
  # mount_uploader :image, ImageUploader
  
  # Delayed job
  # mount_uploader :image, AssetUploader
  # after_save :enqueue
  
  acts_as_taggable

  geocoded_by :postal_code
  after_validation :geocode

  def self.find_by_tag(tag)
    Product.joins(:tags).where('tags.name LIKE ?', "%#{tag}%")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login, except: [:index, :show, :home]

  def index
    choose_search_method

    respond_to do |format|
      format.html
      format.js
    end
  end

  def choose_search_method
    search = params[:search]
    query = "LOWER(products.name) LIKE LOWER(?) OR LOWER(products.description) LIKE LOWER(?) OR tags.name LIKE LOWER(?)"
    if params[:tag]
     @products = Product.find_by_tag(params[:tag]).distinct(:product_id)
    elsif params[:latitude] && params[:longitude] && search
     @products = Product.joins("LEFT OUTER JOIN taggings ON products.id = taggings.taggable_id").joins("LEFT OUTER JOIN tags ON taggings.tag_id = tags.id").where(query, "%#{search}%", "%#{search}%", "%#{search}%").distinct(:product_id).near([params[:latitude], params[:longitude]], params[:proximity], units: :km)
    elsif (params[:noloc] == "true") && search
     @products = Product.joins("LEFT OUTER JOIN taggings ON products.id = taggings.taggable_id").joins("LEFT OUTER JOIN tags ON taggings.tag_id = tags.id").where(query, "%#{search}%", "%#{search}%", "%#{search}%").distinct(:product_id)
    else
     @products = Product.limit(10).order("RANDOM()")
    end

    @products = @products.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
    @conversation = Conversation.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.garden = current_user.garden
    @product.postal_code = @product.garden.postal_code
    if @product.save
      redirect_to garden_path(@product.garden)
    else
      redirect_to garden_path(current_user.garden)
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def home
    session[:location] = [params[:latitude], params[:longitude]]
    @products = Product.near(session[:location], 10, units: :km).limit(10).order("RANDOM()")
  end

  def imagedelete
    @product = Product.find(params[:product_id])
    @product.remove_image!
    @product.save
    redirect_to product_path(@product)
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :trade_info, :image, :tag_list)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_carousel.html.erb
<% @products.each do |product| %>
  <div class="carousel-card">
    <div class="carousel-pic">
      <%= image_tag product.image %>
    </div>
    <div class="carousel-info">
      <ul>
        <% if session_location != nil %>
          <li><%= product.distance_to(session_location, :km).round(2) %>km</li>
        <% end %>
        <li class="truncate"><%= link_to product.name, product_path(product) %></li>
        <li class="truncate">by: <%= product.garden.user.name %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/products/_displayproduct.html.erb
<h1><%= @product.name %></h1>

<div class="product-show-grid">
  <%= image_tag @product.image, class: "product-show-img" %>
</div>

<div class="product-detail-grid">
  <div>
      <em>Tags: <%= @product.tag_list %></em>
  </div>
  <div class="product-description">
    <%= @product.description %>
    <%= @product.trade_info %>
  </div>

  <div class="social-buttons">
    <ul>
      <li>
        <!-- Twitter -->
        <a href="http://twitter.com/home?status=<%= product_url(@product) %>" title="Share on Twitter" target="_blank" class="btn btn-twitter"><i class="fa fa-twitter"></i> Twitter</a>
      </li>
      <li>
        <!-- Facebook -->
        <a href="https://www.facebook.com/sharer/sharer.php?u=<%= product_url(@product) %>" title="Share on Facebook" target="_blank" class="btn btn-facebook"><i class="fa fa-facebook"></i> Facebook</a>
      </li>
      <li>
        <!-- Google+ -->
        <a href="https://plus.google.com/share?url=<%= product_url(@product) %>" title="Share on Google+" target="_blank" class="btn btn-googleplus"><i class="fa fa-google-plus"></i> Google+</a>
      </li>
    </ul>
  </div>

  <button class="product-show-btn">
    <%= link_to 'View Garden', garden_path(@product.garden) %>
  </button>

</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/products/_loadingwheel.html.erb
<% 10.times do |i| %>
  <div class="carousel-card">
    <div class="carousel-pic">
      <%= image_tag ("loading.gif") %>
    </div>
  </div>
<% end %>

app/views/products/_messageform.html.erb
<%= form_for([@conversation]) do |f| %>
  <div class="make-request">
  What would you like to trade for <%= @product.name %>?
  </div>
  <div class="field">
    <%= f.text_area :request, class: "product-show-convo" %>
  </div>
    <%= f.hidden_field :product_id, {value: @product.id} %>
    <%= f.hidden_field :sender_id, {value: current_user.id} %>
    <%= f.hidden_field :receiver_id, {value: @product.garden.user.id} %>
  <div class="product-show-btn">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="product-card">
  <div class="product-card-pic">
    <%= link_to product_path(product) do %>
      <% image_tag product.image %>
    <% end %>
  </div>
  <div class="product-info">
    <h3><%= link_to product.name, product_path(product) %></h3>
    <div class="distance">
      <%= product.distance_to(session_location, :km).round(2) %> km
    </div>
    <div class="product-description">
      <%= product.description %>
    </div>
    <div class="trade-info">
      <strong>Trade info:</strong> <%= product.trade_info %>
    </div>

  </div>
</div>

app/views/products/edit.html.erb
<h2 class="main-title">Edit product</h2>
<%= render 'gardens/newproductform' %>

app/views/products/home.html.erb
<div class="banner-container">
<div class="banner">
  <div class="banner-text">
    <h1 class="type-system-rounded">Fresh From Your Garden<br>
    Trade What You Grow</h1>
  </div>
</div>
</div>

<div class="carousel-title">
  <h3>Products Near You</h3>
</div>

<div class="carousel-container">
  <div class="carousel">
    <%= render 'loadingwheel' %>
  </div>
</div>

<div class="category-title">
  <h3>Browse by Category</h3>
</div>

<div class="category-container">
  <div class="category-thumb" id="leafy-green-btn">
    <%= link_to products_path(:tag => "leafy green") do %>
      <div class="btn-mask">
        <h5>Leafy Green</h5>
      </div>
    <% end %>
  </div>

  <div class="category-thumb" id="roots-btn">
    <%= link_to products_path(:tag => "root") do %>
      <div class="btn-mask">
        <h5>Roots</h5>
      </div>
    <% end %>
  </div>

  <div class="category-thumb" id="fruit-veggie-btn">
    <%= link_to products_path(:tag => "fruit vegetable") do %>
      <div class="btn-mask">
        <h5>Fruit Vegetables</h5>
      </div>
    <% end %>
  </div>

  <div class="category-thumb" id="berries-btn">
    <%= link_to products_path(:tag => "berries") do %>
      <div class="btn-mask">
        <h5>Berries</h5>
      </div>
    <% end %>
  </div>

  <div class="category-thumb" id="pomes-btn">
    <%= link_to products_path(:tag => "pomes") do %>
      <div class="btn-mask">
        <h5>Pomes</h5>
      </div>
    <% end %>
  </div>

  <div class="category-thumb" id="citrus-btn">
    <%= link_to products_path(:tag => "citrus") do %>
      <div class="btn-mask">
        <h5>Citrus</h5>
      </div>
    <% end %>
  </div>
</div>

<script>

// 1. if there is no lat/lng in the cookie cache, then
// we need to call getLocationFromBrowser() with lat/lng set from the browser.

// 2. if there IS lat/lng in the cookie cache, then
// we need to call getProducts() with lat/lng from the cookie cache.

function getLocationFromBrowser(){
  if ("geolocation" in navigator) {
    navigator.geolocation.getCurrentPosition(geolocationSuccess);
  }else{
    alert("Browser does not support geocoding");
  }
  setTimeout(getLocationFromBrowser, 1800000);
}

function geolocationSuccess(position, isLocationDisabled) {
  console.log("In geolocationSuccess!");

  var latitude  = position.coords.latitude;
  var longitude = position.coords.longitude;

  var expiry = expireCookie(20);

  $.cookie('latitude', latitude, { expires: expiry });
  $.cookie('longitude', longitude, { expires: expiry });

  getProducts(longitude, latitude);
}

function expireCookie(minutes) {
  var date = new Date();
  var min = minutes;
  return date.setTime(date.getTime() + (min * 60 * 1000));
}

function getProducts(longitude, latitude) {
  $.ajax({
    url: '/products/home',
    method: 'GET',
    data: {
      longitude: longitude,
      latitude: latitude
    },
    dataType: 'script'
  });
}

if($.cookie('latitude') == undefined && $.cookie('longitude') == undefined ){
  getLocationFromBrowser();
} else {
  getProducts($.cookie('longitude'), $.cookie('latitude'));
}

</script>

app/views/products/home.js.erb
$(".carousel").html('<%= j(render 'carousel') %>')

app/views/products/index.html.erb
<h1 class="main-title">Products</h1>
<div class="search-bar">
  <%= form_tag products_path, method: :get, id: 'search-form'  do %>
    <%= text_field_tag :search, params[:search], id: 'search-field' %>
    <%= range_field_tag(:proximity, :distance, :in => 0..30, :step => '5', :value => '10') %>
    <div class="rangevalue"></div>
    <%= submit_tag "search", value: "product-search", id: "search-button" %>
  <% end %>
</div>

<div id="products" class="js-masonry">
	<%= render @products %>
</div>

<div class="pagination-links">
  <%= paginate @products %>
</div>

app/views/products/index.js.erb
$("#products").html('<%= j(render @products) %>');
var productCard = $('#products');

productCard.imagesLoaded(function(){
  productCard.masonry("reloadItems");

  productCard.masonry({
    itemSelector: '.product-card',
    columnWidth: 145,
    isFitWidth: true,
    gutter: 8
  });
});

$(".pagination-links").html('<%= j paginate @products %>');

app/views/products/masonry.html.erb
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.js"></script>
  <link rel="stylesheet" href="css/masonry.css">
  <title></title>
</head>
<body>
  <h1>Masonry - layout method</h1>
  <p>Click to toggle item size</p>
  <div class="grid">
    <div class="grid-item"></div>
    <div class="grid-item grid-item--width2 grid-item--height2"></div>
    <div class="grid-item grid-item--height3"></div>
    <div class="grid-item grid-item--height2"></div>
    <div class="grid-item grid-item--width3"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item grid-item--height2"></div>
    <div class="grid-item grid-item--width2 grid-item--height3"></div>
    <div class="grid-item"></div>
    <div class="grid-item grid-item--height2"></div>
    <div class="grid-item"></div>
    <div class="grid-item grid-item--width2 grid-item--height2"></div>
    <div class="grid-item grid-item--width2"></div>
    <div class="grid-item"></div>
    <div class="grid-item grid-item--height2"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item grid-item--height3"></div>
    <div class="grid-item grid-item--height2"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item grid-item--height2"></div>
  </div>
</body>
</html>

app/views/products/new.html.erb
<div>
	<%= form_for(@product) do |f| %>
	<div>
    <div>
      <%= f.label :tag_list %>
      <%= f.text_field :tag_list %>
    </div>
	 	<div>
 			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
   		<div>
   			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
  		<div>
  			<%= f.label :trade_info %>
  	  		<%= f.text_area :trade_info %>
  	 	</div>
  	<%= f.submit %>
		<% end %>
	</div>
</div>

app/views/products/show.html.erb
<div class="product-grid">
  <%= render 'displayproduct' %>

    <div class="product-show-grid">
      <% if @product.garden.user == current_user %>
        <div>
          <%= form_for(@product) do |f| %>
            <div>
              <%= f.label :tag_list, :class => 'text-label' %>
              <%= f.text_field :tag_list,:class => 'text-field' %>
            </div>
            <div class="update-btn edit-controls">
              <li><%= f.submit "Update" %></li>
              <% end %>
              <li> <%= button_to 'Edit', edit_product_path(@product), method: :get %></li>
              <li><%= button_to "Delete", product_path(@product) , method: :delete, data: {confirm: "Are you sure you want to delete this product?"} %></li>
            </div>
        </div>
      <% end %>
      <% if current_user && @product.garden.user != current_user %>
        <div class="product-show-text">
          <%= render 'messageform' %>
        </div>
      <% end %>
    </div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>