config/routes.rb
Rails.application.routes.draw do
  root 'products#home'
  get 'home' => 'products#home'

  get 'oauths/oauth'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions

  resources :products do
    get 'imagedelete'
    collection do
      get 'home'
    end
  end
  resources :conversations
  resources :messages
  resources :trades

	resources :gardens, only: [:show, :new, :index, :create, :destroy]
  resources :users, only: [:show, :new, :create, :destroy, :edit, :update] #do
  #   member do
  #     get 'inbox' => 'user#inbox', :as => :inbox
  #   end
  # end

  get '/users/:id/inbox', to: 'users#inbox', as: 'inbox'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    session[:location] = nil
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<div class="login-form">
  <%= form_tag user_sessions_path, :method => :post do %>
  <div class="login-grid">
    <div class="login-field">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>
    <div class="login-field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
  </div>
  <%= render partial: 'shared/flash' %>
  <div class="user-login-btn">
    <%= submit_tag "Login", value: "login", class: "login-btn" %>
  </div>
  <% end %>
</div>
<div class="register-btn">
  <%= button_to "Register", new_user_path, method: :get %>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/location.js.erb
location saved

app/views/user_sessions/new.html.erb
<%= render 'form' %>