config/routes.rb
Rails.application.routes.draw do
  root 'products#home'
  get 'home' => 'products#home'

  get 'oauths/oauth'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions

  resources :products do
    get 'imagedelete'
    collection do
      get 'home'
    end
  end
  resources :conversations
  resources :messages
  resources :trades

	resources :gardens, only: [:show, :new, :index, :create, :destroy]
  resources :users, only: [:show, :new, :create, :destroy, :edit, :update] #do
  #   member do
  #     get 'inbox' => 'user#inbox', :as => :inbox
  #   end
  # end

  get '/users/:id/inbox', to: 'users#inbox', as: 'inbox'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	has_many :messages
	belongs_to :product
	belongs_to :sender, class_name: User
	belongs_to :receiver, class_name: User
	has_one :trade
end

app/models/garden.rb
class Garden < ActiveRecord::Base
  belongs_to :user
  has_many :products
  belongs_to :garden
  geocoded_by :postal_code
  after_validation :geocode
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :sender, class_name: User
  validates :content, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :conversations
  belongs_to :garden
  belongs_to :trade
  validates :name, presence: true
  
  # For AWS upload
  # mount_uploader :image, ImageUploader
  
  # Delayed job
  # mount_uploader :image, AssetUploader
  # after_save :enqueue
  
  acts_as_taggable

  geocoded_by :postal_code
  after_validation :geocode

  def self.find_by_tag(tag)
    Product.joins(:tags).where('tags.name LIKE ?', "%#{tag}%")
  end

end

app/models/trade.rb
class Trade < ActiveRecord::Base
	belongs_to :product
	belongs_to :buyer, class_name: User
	belongs_to :seller, class_name: User
	belongs_to :conversation
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  before_save { self.email = email.downcase }
  # before_save { self.email = self.email.downcase }  # same as above
  # We can omit the 2nd self because Rails does this for us.

  # For AWS upload
  # mount_uploader :image, ImageUploader
  # mount_uploader :image, AssetUploader
  # after_save :enqueue

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  has_one :garden
  has_many :products, through: :garden
  has_many :messages, through: :product
  has_many :trades

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, presence: true
  validates :email, uniqueness: {case_sensitive: false}
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: "not a valid email address" }
  validates :name, presence: true

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  skip_before_filter :require_login, only: [:index, :show]

  def index
    choose_search_method

    respond_to do |format|
      format.html
      format.js
    end
  end

  def choose_search_method
    if params[:latitude] && params[:longitude]
      @gardens = Garden.near([params[:latitude], params[:longitude]], params[:proximity], units: :km)
    elsif !params[:latitude]
      @gardens = Garden.all
    end
  end

  def show
    if params[:latitude]
      @lat = params[:latitude]
      @long = params[:longitude]
    end

    @garden = Garden.find(params[:id])
    @products = Garden.find(params[:id]).products
    @product = Product.new
    @user = @garden.user
  end

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user

    if @garden.save
      redirect_to user_path(@current_user)
    else
      redirect_to user_path(@current_user)
    end
  end

  def destroy
    @garden = Garden.find(params[:id])

    @garden.products.each do |product|
      product.destroy
    end

    @garden.destroy
    redirect_to user_path(current_user)
  end

  private
  def garden_params
    params.require(:garden).permit(:postal_code)
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
skip_before_filter :require_login

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end

  private
  def auth_params
    params.permit(:code, :provider)
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  def new
    @product = Product.find(params[:product])
    @conversation = Conversation.find(params[:conversation])
    @buyer = User.find(params[:buyer])
    @trade = Trade.new
  end

  def index
    @trades_seller_success = Trade.where("seller_id = ? AND success = ?", current_user, true)
    @trades_seller_unsuccessful = Trade.where("seller_id = ? AND success = ?", current_user, false)
    @trades_buyer_success = Trade.where("buyer_id = ? AND success = ?", current_user, true)
    @trades_buyer_unsuccessful = Trade.where("buyer_id = ? AND success = ?", current_user, false)
  end

  def create
    @trade = Trade.create(trade_params)
    @trade.conversation.trade_id = @trade.id
    @trade.conversation.save
    if @trade.save
      redirect_to user_path(current_user)
    else
      render :new
    end

  end

  private
  def trade_params
    params.require(:trade).permit(:negotiation_result, :seller_id, :buyer_id, :product_id, :conversation_id, :success)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.first
      render :new
    end
  end

  def show
    @user = current_user
    @garden = Garden.new
  end

  def inbox
    @sent_conversations = Conversation.where("sender_id = ?", current_user.id)
    @received_conversations = Conversation.where("receiver_id = ?", current_user.id)
    @trades = Trade.where("seller_id = ?", current_user.id)
    @user = current_user

    # create a list of unique products
    @sent_products_list = Product.joins(:conversations).where("sender_id = ?", current_user.id).distinct
    @received_products_list = Product.joins(:conversations).where("receiver_id = ?", current_user.id).distinct
  end

  def destroy
    logout
    @user.garden.products.each do |product|
      product.destroy
    end
    @user.garden.destroy
    @user.destroy

    redirect_to root_path
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<div id="nav">
  <% if current_user %>
    <div>
      Logged in as: <%= current_user.name %>
    </div>
    <div>
      <%= link_to "Logout", :logout, method: :post %>
    </div>
    <div>
      <%= link_to "User Profile", user_path(current_user) %>
    </div>
  <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", :login %> |
    <%= link_to 'Login with Github', auth_at_provider_path(provider: :github) %> |
    <%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %> |
  <% end %>
  <%= link_to "Home", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homegrown</title>
  <meta name="viewport" content="initial-scale=1.0,width=device-width">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Nunito:400,700,300' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Oswald:300' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="header-bar">
    <ul class="nav">
      <% if current_user %>

        <li class="nav-link medium-screen" id="logout">
            <%= link_to "Sign out", :logout, method: :post %>
        </li>

        <li class="nav-link medium-screen">
          <%= link_to 'Profile', user_path(current_user)%>
        </li>

        <li class="nav-button drop-down" id="user-icon">
          <a href="javascript:void(0)"><i class="fa fa-user"></i></a>
          <ul>

            <%= link_to user_path(current_user) do %>
              <li>
                Profile
              </li>
            <% end %>

            <% if current_user.garden %>
              <%= link_to garden_path(current_user.garden) do %>
                <li>
                  Garden
                </li>
              <% end %>
            <% else %>
              <li>
                <span class="disabled">Garden</span>
              </li>
            <% end %>

            <li class="nav-link" id="logout">
              <%= link_to "Sign out", :logout, method: :post %>
            </li>

          </ul>
        </li>

        <li class="nav-link medium-screen">
          <%= link_to 'Inbox', inbox_path(current_user)%>
        </li>

        <li class="nav-button" id="inbox-icon">
          <%= link_to inbox_path(current_user) do %>
            <i class="fa fa-inbox"></i>
          <% end %>
        </li>

        <li class="nav-link medium-screen">
          <% if current_user.garden %>
            <%= link_to "Garden", garden_path(current_user.garden) %>
          <% else %>
            <span class="disabled">Garden</span>
          <% end %>
        </li>

      <% else %>

        <li>
          <div class="modal">
            <label for="modal-1">
              <div class="modal-trigger"> Sign in</div>
            </label>
            <input class="modal-state" id="modal-1" type="checkbox" />
            <div class="modal-fade-screen">
              <div class="modal-inner">
                <div class="modal-close" for="modal-1"></div>
                <ul>
                  <li><i class="fa fa-sign-in"></i><%= link_to "Sign in", :login %></li>
                  <li><i class="fa fa-github"></i> <%= link_to 'Login with Github', auth_at_provider_path(provider: :github) %></li>
                  <li><i class="fa fa-facebook-official"></i> <%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %></li>
                </ul>
              </div>
            </div>
          </div>
        </li>
        <li class="nav-link">
          <%= link_to "Register", new_user_path %>
          <%# link_to "Register", :new_user %>  <!-- same as above line -->
        </li>

      <% end %>

      <li class="nav-button" id="search">
        <%= link_to products_path do %>
          <i class="fa fa-search" ></i>
        <% end %>
      </li>

      <%= link_to root_path do %>
        <div class="homegrown">
        </div>
      <% end %>
    </ul>
  </header>

  <main>
    <%= yield %>
  </main>

  <div class="footer-container">
    <div class="footer-menu">
      <ul>
        <li><i class="fa fa-pinterest-square"></i></li>
        <li><i class="fa fa-facebook-square"></i></li>
        <li><i class="fa fa-tumblr-square"></i></li>
        <li><i class="fa fa-twitter-square"></i></li>
      </ul>
      <% if current_user %>
      |  <%= link_to "Home", home_products_path %>
      | <%= link_to "Products",products_path %>
      |  <%= link_to "Garden", garden_path(current_user) %>
      |  <%= link_to "Profile", user_path(current_user) %>  |
      <% end %>
      <div class="copyright-info">&copy; 2015 Homegrown. All rights reserved. Sponsor by bitmaker Labs</div>
    </div>
  </div>
</body>
</html>

app/views/refills/_type_system_sans.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,400italic,600italic,600,700,700italic,900,300italic,300,200italic,200' rel='stylesheet' type='text/css'>
</head>

<article class="type-system-sans">
  <p class="type">Article Type</p>
  <h1>Article Heading</h1>
  <h2>These override some of the styles specified in the <code>_variables.scss</code> and <code>_typography.scss</code> partials in <a href="//bitters.bourbon.io">Bitters</a>. You can replace the typography variables and the header font specifications in Bitters with these styles. Then you won&rsquo;t need the wrapping class <code>.type-system-name</code>.</h2>
  <p class="date">30 Mar 2014</p>
  <p><span>Lorem ipsum dolor sit amet</span>, consectetur adipisicing elit. Consequatur a, ullam, voluptatum incidunt neque doloremque vel inventore distinctio laudantium harum</a> illo quam nulla dolor alias iure impedit! Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit.
    <a href="javascript:void(0)" class="read-more">Read More <span>&rsaquo;</span></a>
  </p>
  <h3>Subheading lorem</h3>
  <p><span>Consequatur ullam, voluptatum</span> incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit. Accusamus. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit! Accusamus.</p>
  <hr>
  <p class="author">Author Name</p>
</article>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| -%>
  <% if name != 'notice' %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<% end -%>

app/views/shared/_validations.html.erb
<% object.errors.full_messages.each do |error_message| %>
  <%= error_message if object.errors.full_messages.first == error_message %> <br />
<% end %>